on: 
  pull_request:
  push:
    branches:
    - master

name: Windows Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        platform:
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install dependencies
      run: choco install svn hg
    - name: Test
      run: go test -v
      env:
        SKIP_BZR: "true"